export const actionTypes = {
  TODOADD: "post/TODOADD",
  TODOREMOVE: "delete/TODOREMOVE",
  TODOUPDATE: "update/TODOUPDATE",
  TODOUPDATEFINAL: "update/TODOUPDATEFINAL",
  TODOUPDATEFIRST: "update/TODOUPDATEFIRST",
  TODOREMOVEFIRST: "delete/TODOREMOVEFIRST",
  TODOREMOVESEC: "delete/TODOREMOVESEC",
  TODOREMOVEFINAL: "delete/TODOREMOVEFINAL",
};
